### PR TITLE
Add git slides, update tex header, add testing

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Review by vuillaut — COMMENTED** [review]
LGTM

Could you add a post in  `docs/content/posts` following the demo please?

**Comment by maxnoe** [comment]
Sure

**Comment by maxnoe** [comment]
> Could you add a post in docs/content/posts following the demo please?

A post? Or one for git and testing each?

**Comment by maxnoe** [comment]
They were also failing before https://github.com/escape2020/school2022/runs/6588052536?check_suite_focus=true (Expand the run tests section, it says error), but for some strange reason, the build got a green checkmark

**Pull request merged**
