### PR TITLE
Avoid docker builds with every push and avoids duplicated workflows

### PR DESCRIPTION
**Pull request by garciagenrique**
* This was happening due to the detached CI workflows.
* And because I forgot to add on: push: types: - tags on the CI file

### CODE REVIEW

**Review by vuillaut — APPROVED** [review]

**Comment by vuillaut** [comment]
Can you apply the same change to avoid unit testing twice in parallel during pull requests?

**Comment by garciagenrique** [comment]
Indeed the changes I'm making were taken out in this commit 21e1c874998ead9f2b164cf453283aad57284917 @vuillaut. Am I missing something ?

**Comment by vuillaut** [comment]
> Indeed the changes I'm making were taken out in this commit [21e1c87](https://github.com/escape2020/school2022/commit/21e1c874998ead9f2b164cf453283aad57284917) @vuillaut. Am I missing something ?

wait now I am confused, I thought the docker image was already  built for every push as you reported to me last week, so I removed the `on push` trigger.
Now it's building only for merged PRs as it should - so why this PR is needed?

**Comment by vuillaut** [comment]
> > Can you apply the same change to avoid unit testing twice in parallel during pull requests?
> 
> Not sure If I understood you question. You want to avoid testing (which workflow?) during pull requests ? Or that are teste only at pull requests not when merged ?

Unit tests are running twice in parallel (look at this PR for example, 6 checks instead of 3), because it's running for push and PR.

**Comment by garciagenrique** [comment]
> wait now I am confused, I thought the docker image was already built for every push as you reported to me last week, so I removed the `on push` trigger.

I think we didn't understood each other then :)

> Now it's building only for merged PRs as it should - so why this PR is needed?

It is building only for merged PRs but twice, as the PR includes a push too...
I don't think it is necessary that the docker file is re-builded which each single push, but with every merged PR. Taking out the on: push: etc... and having `rules` for `push` triggers the workflow for every push I guess.

**Comment by garciagenrique** [comment]
> > > Can you apply the same change to avoid unit testing twice in parallel during pull requests?
> > 
> > 
> > Not sure If I understood you question. You want to avoid testing (which workflow?) during pull requests ? Or that are teste only at pull requests not when merged ?
> 
> Unit tests are running twice in parallel (look at this PR for example, 6 checks instead of 3), because it's running for push and PR.

The duplication of the unit tests are due to the `Base env test` workflow, not the `Docker image CI` one ;)

**Review by vuillaut — APPROVED** [review]

**Pull request merged**
